### ISSUE TITLE
cl-fastcgi currently broken for Quicklisp

### ISSUE THREAD

**Issue by brown** [KDr2/cl-fastcgi#8]
A recent change introduced a type error that triggers compilation failure with SBCL.  Failure log is here:  http://report.quicklisp.org/2023-11-06/failure-report/cl-fastcgi.html#cl-fastcgi
This pull request fixes the problem:  https://github.com/KDr2/cl-fastcgi/pull/7

**Comment by KDr2** [comment]
fixed by #9.
